"""first migration

Revision ID: ba7820d6767d
Revises:
Create Date: 2024-09-13 11:39:03.631724

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlalchemy_utils

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ba7820d6767d"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "brand",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "character",
        sa.Column("name", sa.String(length=255), nullable=False, unique=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "typeproduct",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "product",
        sa.Column("model", sa.String(length=255), nullable=False),
        sa.Column("typeproduct_id", sa.Integer(), nullable=False),
        sa.Column("brand_id", sa.Integer(), nullable=False),
        sa.Column("dimensions", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), server_default="", nullable=False),
        sa.Column("price", sa.Integer(), nullable=True),
        sa.Column("power", sa.Float(), nullable=True),
        sa.Column("view_stats", sa.Integer(), nullable=True),
        sa.Column(
            "pdf_url", sqlalchemy_utils.types.url.URLType(), nullable=False
        ),
        sa.Column(
            "image_url", sqlalchemy_utils.types.url.URLType(), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("TIMEZONE('utc', now())"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("TIMEZONE('utc', now())"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["brand_id"],
            ["brand.id"],
        ),
        sa.ForeignKeyConstraint(
            ["typeproduct_id"],
            ["typeproduct.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("model"),
    )
    op.create_table(
        "product_character_association",
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("character_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["character_id"],
            ["character.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "product_id", "character_id", name="idx_unique_product_character"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("product_character_association")
    op.drop_table("product")
    op.drop_table("typeproduct")
    op.drop_table("character")
    op.drop_table("brand")
    # ### end Alembic commands ###
