name: sytle_check

on:
  pull_request:
  push:
    branches:
      - develop
      - master
jobs:
  check_style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set-up python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pep8-naming flake8-broken-line flake8-return flake8-isort flake8-docstrings

      - name: Check styles
        run: python -m flake8 --config=./.flake8 ./src
